kinematics:
  shoulder:
    x: 0
    y: 0
    z: 0.235
    roll: 0
    pitch: 0
    yaw: 0
  upperarm:
    x: 0
    y: 0
    z: 0
    roll: 1.570796326589793
    pitch: 0
    yaw: 0
  forearm:
    x: -1.0
    y: 0
    z: 0
    roll: 0
    pitch: 0
    yaw: 0
  wrist_1:
    x: -1.0
    y: 0
    z: 0.1825
    roll: 0
    pitch: 0
    yaw: 0
  wrist_2:
    x: 0
    y: -0.1133
    z: 0
    roll: 1.570796326589793
    pitch: 0
    yaw: 0
